In [14]:
from datascience import *
import numpy as np

In [1]:
def double(x):
    """ Double x """
    return 2*x

In [2]:
double(4)

8

In [5]:
from datascience import *
double(make_array(3,4,5))

array([ 6,  8, 10])

In [4]:
from datascience import *
make_array(3,4,5)

array([3, 4, 5])

In [19]:
def percent(x,total):
    """
    Convert first argument (x) to a percentage of second argument (total). This function divides x by total and multiplies the result by 100 and rounds the results by 2 decimal places. """
    return round((x/total)*100, 2)

In [11]:
percent(4, 16)

25.0

In [12]:
def percents(counts):
    """Convert the values of array argument to percents out of total of array argument """
    total = counts.sum()
    return np.round((counts/total)*100, 2)

In [15]:
percents(make_array(7,10,4))

array([33.33, 47.62, 19.05])

In [20]:
def biggest_difference(array_x):
    """Find the biggest difference in absolute value between to adjacent elements of array_x"""
    diffs = np.diff(array_x)
    absolute_diffs = abs(diffs)
    return max(absolute_diffs)

some_numbers = make_array(2, 4, 5, 6, 4, -1, 1)
big_diff = biggest_difference(some_numbers)
print("The biggest difference is ", big_diff)

The biggest difference is  5


In [21]:
def cut_off_at_100(x):
    """The smaller of x and 100"""
    return min(x, 100)

In [22]:
ages = Table().with_columns(
    "Person", make_array('A', 'B', 'C', 'D', 'E', 'F'),
    'Age', make_array(17, 117, 52, 100, 6, 101)
)
ages

Person | Age
A      | 17
B      | 117
C      | 52
D      | 100
E      | 6
F      | 101

In [23]:
ages.apply(cut_off_at_100,'Age')

array([ 17, 100,  52, 100,   6, 100])

In [25]:
ages.with_column('Cut off Age', ages.apply(cut_off_at_100, 'Age'))

Person | Age  | Cut off Age
A      | 17   | 17
B      | 117  | 100
C      | 52   | 52
D      | 100  | 100
E      | 6    | 6
F      | 101  | 100